spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peerprep?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: peerprep_admin
    password: cs3219_G16_yyds
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
