server:
  port: 8080
  error:
    include-message: always
  servlet:
    session:
      cookie:
        secure: true

spring:
  datasource:
    url: jdbc:mysql://34.87.12.122:3306/peerprep?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: peerprep_admin
    password: adminCS3219g16
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: cs3219g16@gmail.com
    password: g16password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000

custom:
  auth:
    enable: true
  domain:
    backend: "https://peerprep-backend-service-mepxozmoha-as.a.run.app"
    frontend: "https://peerprep-g16.netlify.app"
  email:
    enable: true

interview:
  dayDuration: 10
