steps:
  # maven install
  - name: maven:3.8.3-openjdk-11-slim
    dir: ./peerprep
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  # build docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: ./peerprep
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/peerprep_backend', '.' ]
  # push docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "push", "gcr.io/$PROJECT_ID/peerprep_backend" ]
  # deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'beta', 'run', 'deploy', 'peerprep-backend-service', '--cpu', '4', '--memory', '8Gi', '--timeout', '3600', '--concurrency', '1000', '--min-instances', '1', '--max-instances', '1',  '--platform', 'managed', '--ingress', 'all', '--allow-unauthenticated', '--no-cpu-throttling', '--image', 'gcr.io/$PROJECT_ID/peerprep_backend', '--region', 'asia-southeast1']
images: [ 'gcr.io/$PROJECT_ID/peerprep_backend' ]